# Generated by Django 5.1.7 on 2025-04-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=225)),
                ('receiver_name', models.CharField(max_length=225)),
                ('purpose', models.CharField(choices=[('Package', 'Package'), ('gift', 'gift'), ('Order Letters', 'Order Letters'), ('Confirmation Letters', 'Confirmation Letters'), ('Invitation Letters', 'Invitation Letters'), ('Memos Letters', 'Memos Letters'), ('Recommendation Letters', 'Recommendation Letters')], max_length=225)),
            ],
        ),
    ]
